apiVersion: apps/v1
kind: Deployment
metadata:
  name: unir-devops
spec:
  replicas: 4
  strategy:
    type: RollingUpdate
    rollingUpdate:
       maxSurge: 1
       maxUnavailable: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: unir-devops
  template:
    metadata:
      labels:
        app: unir-devops
    spec:
      containers:
        - image: docker.io/jguimeradev/unir-devops:1.0
          name: flask-docker
          ports:
            - containerPort: 5000
